name: filmzy
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  drift: ^2.12.1
  path: ^1.8.3
  json_serializable: ^6.7.1

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  drift_dev: ^2.12.1
  build_runner: ^2.4.6
